name = "AnnotatedHypergraphs"
uuid = "121eab65-6eab-4c2f-bb7d-b6867ee8c3ea"
authors = ["Jake Harvey <jacob.harvey@mail.mcgill.ca>"]
version = "0.1.0"

[deps]
EcologicalNetworks = "f03a62fe-f8ab-5b77-a061-bb599b765229"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
